name: Deploy Streamlit App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        
      - name: Build Streamlit app
        run: |
          mkdir -p _site
          echo "theme = 'dark'" > _site/config.toml
          cp -r .streamlit _site/.streamlit || true
          cp -r backend _site/backend
          cp -r frontend _site/frontend
          cp -r pages _site/pages
          cp -r src _site/src
          cp -r assets _site/assets || true
          cp -r static _site/static || true
          cp Home.py _site/
          cp requirements.txt _site/
          cp README.md _site/
          
      - name: Create Streamlit config
        run: |
          mkdir -p _site/.streamlit
          echo '[server]' > _site/.streamlit/config.toml
          echo 'headless = true' >> _site/.streamlit/config.toml
          echo 'enableCORS = false' >> _site/.streamlit/config.toml
          echo 'enableXsrfProtection = false' >> _site/.streamlit/config.toml
          echo '[theme]' >> _site/.streamlit/config.toml
          echo 'base = "dark"' >> _site/.streamlit/config.toml
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 